### ISSUE TITLE
HttpRequest, HttpResponse, HttpContext is deprecated

### ISSUE THREAD

**Issue by futurist** [yanzhenjie/AndServer#26]
The sample code in **HTTP API** used deprecated API:

https://github.com/yanzhenjie/AndServer#http-api

Below message will shown on Android studio 2.2+

```
org.apache.http.HttpRequest is deprecated
```

Is this the issue of underlying lib? or sample code itself?

**Comment by yanzhenjie** [comment]
This does not matter if you're using an older version, because `HttpClient` is deprecated in `AndroidSDK`,  but there's still an API in a real phone.

Recently, a new version has been released that uses a new version of `HttpCore` provided by `apache` instead of `HttpClient`. The new version has the following features: Hot Plugging, File Browser, Interceptor, Filter, Http cache.

Welcome to the new version: [http://yanzhenjie.github.io/AndServer](http://yanzhenjie.github.io/AndServer)
